AI4Green/AI4Green

.github/labeler.yml, .github/workflows/label.yml
=> Add issue labels

.github/workflows/test.yml, .gitignore, Webapp/config.py, requirements.in, requirements.txt
Adds tests running on raising PRS
=> Add CI running pytest

.github/pull_request_template.md, .github/workflows/pr.check.work-item-ref.yml
Now the links with devop is active, issues should be linked.
Adds:
- PR template
- PR linker workflow
[AB#98509](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/98509)
=> AB#98509: Link with devops issues

.github/labeler.yml, .github/workflows/deploy.yml, .github/workflows/label.yml, Webapp/sources/__init__.py, Webapp/sources/config.py, docs/deployment.md, startup.sh
Adds the UAT environment.
Includes:
- Adds a pipeline that deploys the app to UAT
- Add a startup command that runs in the app service
- Moves the config into the app code
- Add a docs file to describe this
- Fixes the labeller workflow (got these 2 files the wrong way round)
AB:
- [AB#117089](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/117089)
- [AB#98509](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/98509)
=> AB#117089: Add UAT pipeline

Webapp/sources/blueprints/save_reaction/routes.py, Webapp/sources/static/js/reaction_table/file_handling.js, pyproject.toml
Fixes the file upload/view/delete for a reaction, this functionality hadn't been updated to SQLAlchemy. 
Also cleans up the javascript request types (changes are mostly pre-commit formatting)
=> AB#125037: Fix file upload

.github/workflows/deploy.yml, Webapp/sources/blueprints/reaction_table/routes.py, Webapp/sources/blueprints/save_reaction/routes.py
Fixes two bugs:
- File upload: The previous code assumed the app uses Active Directory, as we do not, a connection string to Azure storage is enough
- Tutorial reaction table: In production, users have added novel compounds and solvents. But the table fails to account for this in the tutorial, when there is no workbook ID to set them to. Quick fix is to add a guard to check for a workbook before we filter on it.
=> AB#125037: Fix tutorial + file upload

Webapp/sources/services/queries/novel_compound.py
novel compound method needed updating after refactor of workbook services
- [AB#134108](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/134108)
=> AB#134108: Novel compound getSmiles method updated

Webapp/sources/blueprints/export_data/routes.py
Fix reaction csv export
- [AB#135703](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/135703)
=> AB#135703: Fixes csv export

Webapp/sources/static/js/reaction_table/reaction_table.js
Fixes the function for calculating volume when using concentration
- [AB#136098](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/136098)
=> AB#136098: Molar volume calculations using concentration

Webapp/sources/blueprints/reaction_table/routes.py
Fixes an issue with imports  from rdkit
- [AB#136096](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/136096)
=> AB#136096: Fixed rdkit import

Webapp/sources/blueprints/solvent_PCA/routes.py, Webapp/sources/services/solvent_surfer/utils.py, poetry.lock, pyproject.toml
Adds statsmodels to dependencies, fixes solvent surfer dropdowns for point selection and from reaction table
[AB#143469](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/143469)
[AB#141692](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/141692)
=> AB#143469: Minor fixes to solvent surfer

Webapp/sources/blueprints/solvent_PCA/routes.py, Webapp/sources/services/solvent_surfer/utils.py, Webapp/sources/static/js/reaction_table/reaction_table.js, Webapp/sources/templates/_reaction_table.html, Webapp/sources/templates/_suggest_solvent_table.html
Fixed bugs in reaction table:
- Links to solvent surfer 
- deleting reagents 
Made suggested solvent table use custom colours
- [AB#144685](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/144685)
- [AB#146027](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/146027)
- [AB#145709](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/145709)
=> AB#141692: Reaction table fix

Webapp/sources/services/solvent_surfer/graph.py, Webapp/sources/services/solvent_surfer/graph_utils.py, Webapp/sources/services/solvent_surfer/utils.py, Webapp/sources/static/js/reaction_table/reaction_reload.js, Webapp/sources/static/js/reaction_table/reaction_table.js
Fixed problems with editing graphs after saving
Fixed problem with colour changes
Stopped Solvent Surfer firing upon reaction reload
- [AB#146875](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/146875)
- [AB#146876](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/146876)
- [AB#146874](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/146874)
=> AB#146874: Graph saving

Webapp/sources/services/ions.py
Fixes a bug when processing ionic compounds
- [AB#152881](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/152881)
=> AB#152881: Fix ion handling bug

Webapp/compound_database/Compound_database_extraction.py, Webapp/sources/blueprints/auth/routes.py, Webapp/sources/commands/commands.py
[AB#161177](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/161177): Old Users Fix
Fixes login issues for users with no "date_of_creation"
- [AB#161177](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/161177)
=> AB#161177: Old Users Fix

Webapp/sources/blueprints/auth/forms.py, Webapp/sources/config.py, Webapp/sources/templates/auth/register.html
Added google recaptcha v2 to prevent false accounts
- [AB#161368](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/161368)
- [AB#160518](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/160518)
=> AB#161368: Recaptcha for registration

Webapp/sources/static/js/reaction_list.js
Wrong reaction Id was being passed for cloning but this is fixed now
- [AB#167767](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/167767)
=> AB#167767: Clone reaction fix

Webapp/sources/services/all_compounds.py, Webapp/sources/services/data_export/metadata.py, Webapp/sources/services/data_export/serialisation.py, Webapp/sources/services/novel_compound.py
fixing issues for exporting and cloning novel reagents
- [AB#168443](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/168443)
=> AB#168443: Novel compound fixes

Webapp/sources/blueprints/export_data/routes.py, Webapp/sources/services/data_export/eln_file.py, Webapp/sources/static/js/export_data.js, Webapp/sources/templates/_summary_table.html
- Fixes an issue with exporting comments
- Reverts changes to summary HTML
- Only looks for first input inside td tags when making html export
- [AB#162141](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/162141)
=> AB#162141: ELN File Fixes

.github/workflows/push-to-devops.yml, Webapp/sources/static/js/home.js, Webapp/sources/templates/macros.html
Fixed new reaction setup from quick access panel
- [AB#177041](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/177041)
=> AB#177041: fixed new reaction setup from quick access

Webapp/sources/blueprints/save_reaction/routes.py, Webapp/sources/static/js/home.js, Webapp/sources/templates/home.html, Webapp/sources/templates/macros.html
Fixing the new reaction modal
- [AB#178074](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/178074)
=> AB#178074: New reaction fix

Webapp/sources/services/data_export/tabular.py, Webapp/sources/services/retrosynthesis/dashboard.py, Webapp/sources/services/retrosynthesis/plotly_elements.py, Webapp/sources/services/retrosynthesis/predictive_chemistry/retrosynthesis_api.py, Webapp/sources/static/js/search.js
- Fix the tabular data export
- Clear search results if no matches
- Wrapper for threaded retrosynthesis
- Change to retrosynthesis loading screen
- [AB#178100](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/178100)
=> AB#178100: Minor fixes for version 1.6

Webapp/sources/blueprints/auth/forms.py, Webapp/sources/services/auth.py, Webapp/sources/static/js/reaction_table/reaction_table.js
- fix bug that prevents summary from loading
- allow users to login with email or password
- [AB#178384](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/178384)
- [AB#178385](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/178385)
=> AB#178384: Summary solvent fix

Webapp/compound_database/pubchem_download.py, Webapp/sources/blueprints/manage_workgroup/routes.py, Webapp/sources/services/data_export/eln_file.py, Webapp/sources/services/data_export/tabular.py, Webapp/sources/services/retrosynthesis/dashboard.py, Webapp/sources/services/retrosynthesis/plotly_elements.py, Webapp/sources/services/retrosynthesis/predictive_chemistry/user_uploaded_routes.py, Webapp/sources/templates/macros.html
- Remove app context from retrosynthesis to avoid using servername
- Minor changes to homepage for mobile use
- QR code URL updated
- Remove empty rows from user uploaded routes
- [AB#178444](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/178444)
=> AB#178444: Version 1.6 Misc fixes

.github/workflows/deploy.yml, Webapp/sources/blueprints/search/routes.py, Webapp/tests/services/test_search.py
- Fix bug when trying to search with invalid SMILES strings
- Update deployment workflow to upload-artifactsv4 and download-artifactsv4
deployment workflow currently uses v3 which is now deprecated 
- [AB#186041](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/186041)
- [AB#186189](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/186189)
- [AB#186208](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/186208)
=> AB#186041: Fix Search and Update GitHub artifacts

Webapp/sources/services/auth.py, Webapp/sources/static/js/polymer.js, Webapp/sources/static/js/reaction_list.js, Webapp/sources/static/js/sketcher/sketcher.js, Webapp/sources/templates/_polymer_reaction_table.html
small fixes:
- missing solvent guide button on rxn table
- removed old console logs
- new error message when smiles parsing fails in sketcher
- changed size of images so delete/clone/etc buttons are visible
- sped up reaction list image generation
- missing import statement 
- [AB#195962](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/195962)
=> AB#195962: Polymer v1 fix

Webapp/sources/blueprints/reaction_list/routes.py, Webapp/sources/blueprints/reaction_table/routes.py, Webapp/sources/services/polymer_novel_compound.py, Webapp/sources/services/sustainability.py, Webapp/sources/static/js/reaction_list.js, Webapp/sources/templates/_polymer_reaction_table.html, Webapp/sources/templates/_polymer_summary_table.html
- remove auth step to save reaction images
- dont allow copolymers
- fix MW calculation
- find polymer repeat unit logic
- remove image for empty reactions
- fix sustainability for polymers with end groups
- [AB#195962](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/195962)
=> AB#195962: Polymer v1 fix 2

Webapp/sources/blueprints/main/routes.py, Webapp/sources/blueprints/reaction_table/routes.py, Webapp/sources/blueprints/save_reaction/routes.py, Webapp/sources/blueprints/summary/routes.py, Webapp/sources/services/polymer_novel_compound.py, Webapp/sources/static/js/polymer.js, Webapp/sources/static/js/reaction_table/autosave.js, Webapp/sources/static/js/reaction_table/reaction_reload.js, Webapp/sources/static/js/sketcher/sketcher.js, Webapp/sources/static/js/sketcher/sketcher_utils.js, Webapp/sources/static/js/summary_table/form_summary_table.js, Webapp/sources/templates/_polymer_reaction_table.html, Webapp/sources/templates/_polymer_summary_table.html, Webapp/sources/templates/demo_sketcher.html, Webapp/sources/templates/sketcher_reload.html, Webapp/sources/templates/workgroup.html
Minor fixes for polymer mode
- [AB#195629](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/195629)
=> AB#195629: Polymer v1 fix

Webapp/sources/blueprints/main/routes.py, Webapp/sources/static/js/auxiliary.js
Change HTTP method from get to patch for the privacy policy acceptance
- [AB#206209](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/206209)
=> AB#206209: Change HTTP method from get to patch

Webapp/sources/templates/general/home.html, Webapp/sources/templates/general/landing_page.html, Webapp/sources/templates/macros/modals.html, Webapp/sources/templates/reactions/_saved_reactions.html
- Restructured and minor tidies to HTML
- Non-colour responsiveness for navbar
- Increased accessibility of navbar
- Minor CSS tidies
- https://github.com/AI4Green/AI4Green/pull/120
- [AB#206570](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/206570)
=> AB#206570: Non-colour responsiveness and titles

.github/workflows/deploy.yml, Webapp/sources/__init__.py
Use werkzeug ProxyFix to get flask_oidc redirects to use correct scheme (https)
- [AB#213760](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/213760)
=> AB#213760: Https for OIDC

Webapp/compound_database/Compound_database_extraction.py, Webapp/migrations/versions/fd539899cb90_copolymers.py
Fixes issues experiences during reaction setup 
- type error from copolymer migration script
- Updated pubchem seed script to match pubchem version
- [AB#213002](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/213002)
=> AB#213002: Set up fixes

Webapp/sources/blueprints/main/routes.py, Webapp/sources/blueprints/summary/routes.py, Webapp/sources/services/sustainability.py
-fixed atom economy calculation
-fixed quick access icons 
- [AB#213745](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/213745)
=> AB#213745: Copolymer fix

Webapp/sources/services/reaction_editing_history.py
add workgroup field to ReactionEditMessage
- [AB#213562](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/213562)
=> AB#213562: add workgroup to ReactionEditMessage

Webapp/sources/services/reaction.py
Fixing a minor typo that causes reaction reviews to crash
- [AB#216184](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/216184)
=> AB#216184: fix typo

Webapp/sources/templates/email/reaction_approval_request.html
Fixed typo in email sent upon reaction review
- [AB#216184](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/216184)
=> AB#216184: fix typo again

.github/workflows/deploy.yml, Webapp/sources/templates/email/reaction_approval_request.html, Webapp/sources/templates/email/reaction_approval_response.html
Fixed links in review emails
- [AB#216184](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/216184)
=> AB#216184: Approval email fix

.github/workflows/audit-log-deploy.yml
update audit log deployment actions to enable federated credentials
- [AB#216486](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/216486)
=> AB#216486: audit log deployment - change federated identity

.github/workflows/publish-ai4green-kafka-connect.yml, .github/workflows/publish-ai4green-minio.yml
- Add directory to paths to the dockerfiles
- [AB#216542](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/216542)
=> AB#216542: Bugfix/images not publishing

Webapp/sources/__init__.py, Webapp/sources/services/data_access_history.py, Webapp/sources/services/message_queue/producers.py, Webapp/sources/services/message_queue/serde.py, Webapp/sources/services/reaction_editing_history.py
- Uncomment logic for sending audit messages to the azure queue
- Fix any errors from the change over
- [AB#217857](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/217857)
=> AB#217857: Use azure queue in app

.github/workflows/push-audit-log-compressor.yml
forgot to put the build context in the last PR
- [AB#218533](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/218533)
=> AB#218533: update compressor deployment pt 2

workers/audit_log_compressor/poetry.lock, workers/audit_log_compressor/pyproject.toml
added azure-storage-queue to dependencies
- [AB#218533](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/218533)
=> AB#218533: update compressor deployment pt 4

Webapp/sources/services/utils.py, Webapp/sources/templates/general/privacy_notice.html
updated privacy policy for the audit log and changed privacy policy date
- [AB#219934](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/219934)
=> AB#219934: change privacy policy

workers/audit_log_deleter/audit_log_deleter.py, workers/audit_log_saver/audit_log_saver.py
Remove overly frequent log statements from audit log saver and deleter
- [AB#222699](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/222699)
=> AB#222699: Reduce log writing

.github/workflows/deploy-audit-log-deleter.yml, .github/workflows/deploy-audit-log-saver.yml
Add revision suffixes to deleter and saver deployment workflows so they actually update in azure
- [AB#222731](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/222731)
=> AB#222731: Add revision suffix
